print ("Hello. Welcome to my quiz about animals.")
print("               /'.    .'\                ")
print("               \( \__/ )/                ")
print("         ___   / (.)(.) \                ")
print("    _.-`_  `-.|  ____  |.-`  _`‘-._     ")
print(" .-'.-'//||`'-.\  V--V  /.-'`||\\'-.'-.  ")
print("`'-'-.// ||    / .___.  \    || \\.-'-'` ")
print("      `-.||_.._|        |_.._||.-'       ")
print("              \ ((  )) /                 ")
print("           jgs  '.    .'                 ")
print("                  `\/`                   ")

question1 = input("What is your favourite animal?")
question2 = input("")