print ("Hello. Welcome to my quiz about animals.")
print("               /'.    .'\                ")
print("               \( \__/ )/                ")
print("         ___   / (.)(.) \                ")
print("    _.-`_  `-.|  ____  |.-`  _`‘-._     ")
print(" .-'.-'//||`'-.\  V--V  /.-'`||\\'-.'-.  ")
print("`'-'-.// ||    / .___.  \    || \\.-'-'` ")
print("      `-.||_.._|        |_.._||.-'       ")
print("              \ ((  )) /                 ")
print("           jgs  '.    .'                 ")
print("                  `\/`                   ")

question1 = input("What is your favourite animal?")
print ("Oh!I like " + question1 + " ,too.That's a great animal.")
question2 = input("Why do you like it?")
print ("Sounds interesting.It's a meaningful reason.")

question2 = input("")